name: Version and Release

on:
  push:
    branches:
      - main
      - electron

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Electron dependencies
        working-directory: ./electron
        run: npm install

      - name: Build Electron app
        working-directory: ./electron
        run: npm run package:win

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        id: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }}
          name: Release ${{ steps.tag.outputs.new_tag }}
          draft: false
          prerelease: false
          files: |
            ./electron/out/citizenstats-win32-x64/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
